---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(viridis)
library(RColorBrewer)

```
```{r}
data(state)
state.name
```


```{r}
data <- read.csv("../Bird_strikes.csv")
data$AirportName <- factor(data$AirportName)
data$OriginState <- factor(data$OriginState)
data$AirportRegion <- rep("", times = nrow(data))
data$AircraftType <- factor(data$AircraftType)
data$FlightPhase <- factor(data$FlightPhase)
data$Engines <- as.numeric(data$Engines)
data$ConditionsPrecipitation <- factor(data$ConditionsPrecipitation)
data$ConditionsSky <- factor(data$ConditionsSky)
data$PilotWarned <- factor(data$PilotWarned)
#data$AirportName %>% table()
data
```


```{r}
lr <- lm(NumberStruckActual ~ Altitude + Engines + FlightPhase + ConditionsPrecipitation+ ConditionsSky + PilotWarned + AirportRegion, data = data)
summary(lr)
```
```{r}
levels(data$AirportRegion)
```

### map stuff

```{r}
library(maps)
library(ggplot2)
```




```{r}
region.adder <- function(df, state){
  northeast <- c("maine", "new hampshire", "vermont", "massachusetts", "rhode island", "connecticut", "new york", "new jersey", "pennsylvania", "delaware", "maryland")
  west <- c("washington", "california", "oregon", "idaho", "montana", "wyoming", "utah", "nevada", "colorado")
  southwest <- c("arizona", "new mexico", "texas", "oklahoma")
  southeast <- c("west virginia", "virginia", "kentucky", "north carolina", "south carolina", "arkansas", "louisiana", "mississippi", "alabama", "georgia", "florida", "tennessee")
  midwest <- c("north dakota", "south dakota", "minnesota", "wisconsin", "michigan", "nebraska", "kansas", "iowa", "missouri", "illinois", "indiana", "ohio")
  alaska <- c("alaska")
  hawaii <- c("hawaii")
  region <- rep(NA, nrow(df))
  
  for (i in 1:nrow(df)){
    if (df$OriginState[i] %in% northeast) region[i] = "northeast"
    else if (df$OriginState[i] %in% west) region[i] = "west"
    else if (df$OriginState[i] %in% southwest) region[i] = "southwest"
    else if (df$OriginState[i] %in% southeast) region[i] = "southeast"
    else if (df$OriginState[i] %in% midwest) region[i] = "midwest"
    else if (df$OriginState[i] %in% alaska) region[i] = "alaska"
    else if (df$OriginState[i] %in% hawaii) region[i] = "hawaii"
    else region[i] = NA
    }
  return (region)
}

```

```{r}
data_us_only <- data[data$OriginState != "",]
data_us_only <- data_us_only[data_us_only$OriginState %in% state.name, ]
data_us_only <- data_us_only[!data_us_only$OriginState %in% c("Alaska", "Hawaii"), ]

data_us_only
```

```{r}
data_us_only$OriginState <- as.character(data_us_only$OriginState)
data_us_only$OriginState <- tolower(data_us_only$OriginState)
data_us_only$OriginState <- factor(data_us_only$OriginState)
data_us_only$region <- region.adder(data_us_only, OriginState)

data$OriginState[5]
data_us_only
```
### Question a.

```{r}
lr <- lm(NumberStruckActual ~ Altitude + Engines + FlightPhase + ConditionsPrecipitation+ ConditionsSky + PilotWarned + region, data = data_us_only)
summary(lr)
```



```{r}
library(usmap)
state <- map_data("state")

```

```{r}
merged_data <- left_join(state, data_us_only[, c("OriginState", "NumberStruckActual", "region")], 
                     by = c("region" = "OriginState"))
```

```{r}
state_avg <- merged_data %>%
  group_by(region) %>%
  summarize(avg_struck = mean(NumberStruckActual, na.rm = TRUE))

merged_data <- merged_data %>%
  left_join(state_avg, by = "region") 

state_max <- merged_data %>%
  group_by(region) %>%
  summarize(max_struck = max(NumberStruckActual, na.rm = TRUE))

merged_data <- merged_data %>%
  left_join(state_max, by = "region") 


region_avg <- merged_data %>%
  group_by(region.y) %>%
  summarize(region_avg = mean(NumberStruckActual, na.rm = TRUE))

# Join the calculated average values back to the merged_data dataframe
merged_data <- merged_data %>%
  left_join(region_avg, by = "region.y")
```


```{r}
ggplot(merged_data, aes(x=long, y=lat, fill = avg_struck, group=group)) + 
  geom_polygon(color = "white") + 
  ggtitle('Average Number of Birds Struck per Incident by State') + 
  scale_fill_viridis(name = "Avg # Struck", limits = c(1, 13)) +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5)) 

```

```{r}
ggplot(merged_data, aes(x=long, y=lat, fill = region_avg, group=group)) + 
  geom_polygon(color = "white") + 
  ggtitle('Average Number of Birds Struck per Incident by Region') + 
#  scale_fill_continuous(low = "lightblue", high = "darkblue", name = "Avg # Struck") +
    scale_fill_viridis(name = "Avg # Struck", limits = c(1, 13)) +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5)) 
```


```{r}
ggplot(merged_data, aes(x=long, y=lat, fill = max_struck, group=group)) + 
  geom_polygon(color = "white") + 
  ggtitle('Maximum Number of Birds Struck per Incident by State') + 
  scale_fill_viridis(name = "Max # Struck") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5)) 
```
Defining the regions of the US
```{r}
df.region <- map_data("state")
df.region$state <- df.region$region
df.region$region <- region.adder(df.region, state)

df.region <- df.region[!is.na(df.region$region), ]

g <- ggplot(df.region, aes(x = long, y = lat, group = group, fill = region)) +
geom_polygon(color="black") +
  guides(na.translate = FALSE) +
  theme_minimal() +
  ggtitle("Regions of the United States") +
  theme(axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid = element_blank(),
      plot.title = element_text(hjust = 0.5))
g
```


```{r}


anova <- aov(NumberStruckActual ~ region, data_us_only)
summary(anova)
```
```{r}
tukey <- TukeyHSD(anova)
tukey
```



